"""
Finding + FindingAnnotation + AssessmentPublication models.

These are the Phase 5 data layer for the consultant override workflow
(audit H11 + H12 + R&P §1 consultant role + C13/C14 edit-window rules).

Why three tables:

- `findings` is the canonical, post-scoring representation of one
  recommendation. Replaces the JSON-blob storage on Assessment.result_json
  (the blob stays as a frozen snapshot for reproducibility). One row per
  finding. Every score run regenerates rows for that assessment.

- `finding_annotations` is the consultant's edit layer on top. One row per
  edit decision (confirmed / severity_adjusted / dismissed / replaced).
  Status governs how the customer-facing render differs from the engine's
  raw output. Annotations are append-only -- the latest is authoritative,
  but earlier ones stay for audit.

- `assessment_publications` records when a consultant publishes the report
  to the customer. Existence of the row enforces R&P C14 (annotation
  edit-window closes on publish).
"""

from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import backref, relationship

from .base import Base


# Finding source: did this come from the engine, or did a consultant add
# it as a custom finding?
FINDING_SOURCE_ENGINE = "engine"
FINDING_SOURCE_CONSULTANT = "consultant"


# Annotation statuses. Match the design's pill labels in
# components/consultant/atoms.tsx so the wiring stays one-to-one.
ANNOTATION_CONFIRMED = "confirmed"
ANNOTATION_SEVERITY_ADJUSTED = "severity_adjusted"
ANNOTATION_DISMISSED = "dismissed"
ANNOTATION_REPLACED = "replaced"

ALL_ANNOTATION_STATUSES = (
    ANNOTATION_CONFIRMED,
    ANNOTATION_SEVERITY_ADJUSTED,
    ANNOTATION_DISMISSED,
    ANNOTATION_REPLACED,
)


class Finding(Base):
    """
    One finding belonging to an assessment. Either generated by the
    scoring engine or added manually by a consultant.
    """

    __tablename__ = "findings"
    __table_args__ = (
        Index("ix_findings_assessment_dimension", "assessment_id", "dimension_id"),
    )

    id = Column(Integer, primary_key=True, index=True)
    assessment_id = Column(
        Integer,
        ForeignKey("assessments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    dimension_id = Column(String(16), nullable=False)
    # Stable identifier across re-scorings of the same logical finding.
    # Allows gap-resolution comparisons in a future assessment trend
    # chart (audit H11). Engine populates this via a deterministic hash
    # of dimension + severity + finding_text; consultant-added findings
    # generate one at insert time.
    finding_template_id = Column(String(32), nullable=True, index=True)

    severity = Column(String(16), nullable=False)
    finding_text = Column(Text, nullable=False)
    recommendation = Column(Text, nullable=True)
    regulatory_risk = Column(Text, nullable=True)
    typical_consulting_hours = Column(Integer, nullable=True)
    upsell_hook = Column(Text, nullable=True)

    source = Column(String(16), nullable=False, default=FINDING_SOURCE_ENGINE)
    # Dimension score that triggered this finding. Preserves engine context
    # so the consultant sees "fired at score 0.8" without joining back to
    # result_json.
    score = Column(Float, nullable=True)

    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    assessment = relationship("Assessment", backref="findings")
    annotations = relationship(
        "FindingAnnotation",
        back_populates="finding",
        cascade="all, delete-orphan",
        order_by="FindingAnnotation.created_at",
    )

    def __repr__(self) -> str:
        return (
            f"<Finding id={self.id} assessment_id={self.assessment_id} "
            f"dim={self.dimension_id} severity={self.severity}>"
        )


class FindingAnnotation(Base):
    """
    A consultant's edit on top of a Finding. Append-only; the latest row
    (per finding) is authoritative for the customer-facing render.
    """

    __tablename__ = "finding_annotations"
    __table_args__ = (
        Index("ix_finding_annotations_finding_created", "finding_id", "created_at"),
    )

    id = Column(Integer, primary_key=True, index=True)
    finding_id = Column(
        Integer,
        ForeignKey("findings.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    consultant_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    status = Column(String(32), nullable=False)

    # For status=severity_adjusted: the new severity.
    new_severity = Column(String(16), nullable=True)

    # For status=replaced: any of these may carry the consultant's
    # rewritten text. Null means "leave the engine's value untouched."
    new_finding_text = Column(Text, nullable=True)
    new_recommendation = Column(Text, nullable=True)
    new_regulatory_risk = Column(Text, nullable=True)
    new_hours = Column(Integer, nullable=True)

    # Required when status != confirmed. Surfaces in the audit log + the
    # consultant console history view + (for dismissed) feeds the rules
    # library improvement loop.
    rationale = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    finding = relationship("Finding", back_populates="annotations")

    def __repr__(self) -> str:
        return (
            f"<FindingAnnotation finding_id={self.finding_id} "
            f"status={self.status}>"
        )


class AssessmentPublication(Base):
    """
    Marker that the assessment's report has been published to the customer.
    Existence of the row enforces R&P C14: no further consultant
    annotations after publish (a separate "republish" / new-version flow
    will land later, out of scope for Phase 5).
    """

    __tablename__ = "assessment_publications"
    __table_args__ = (
        UniqueConstraint("assessment_id", name="uq_publications_assessment"),
    )

    id = Column(Integer, primary_key=True, index=True)
    assessment_id = Column(
        Integer,
        ForeignKey("assessments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    published_by_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    published_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    cover_note = Column(Text, nullable=True)
    # Republish counter — bumps each time the consultant publishes after
    # an unpublish-and-edit cycle. Outstanding share links are revoked at
    # version-bump time so old recipients don't silently see new content.
    version = Column(Integer, default=1, nullable=False)
    # When set, the report is "in revision" — the row exists for version
    # continuity but the C14 edit lock is lifted and customers should see
    # the previous published version, not the in-flight changes. Cleared
    # again on republish, with version bumped.
    unpublished_at = Column(DateTime, nullable=True)

    # uselist=False on the BACKREF (the Assessment.publication side) so
    # accessing Assessment.publication returns a single row or None,
    # not a list. The forward side (AssessmentPublication.assessment) is
    # naturally many-to-one and doesn't need uselist tweaks.
    assessment = relationship(
        "Assessment",
        backref=backref(
            "publication",
            uselist=False,
            cascade="all, delete-orphan",
            single_parent=True,
        ),
    )

    def __repr__(self) -> str:
        return f"<AssessmentPublication assessment_id={self.assessment_id}>"


class ShareLink(Base):
    """
    Read-only signed URL to a published assessment report (R&P C21).

    Issued by an org admin so external recipients (a board, a regulator,
    an auditor) can read the report without an account. The token in the
    URL is the access credential — anyone holding it can read the bound
    report until it expires or is revoked. Therefore:

      - The token is generated with secrets.token_urlsafe(32) — 256 bits of
        entropy, indistinguishable-from-random.
      - We DO log every access (who hit the URL, when, from what IP).
      - We DO NOT include the token in the audit-log context — only its id.
        Don't write the access credential into a different access surface.
      - Revocation is a flag, not a delete; the audit history needs the row.

    The link is bound to the assessment, not to a specific publication row.
    AssessmentPublication has a uniqueness constraint on assessment_id, so
    "the publication" is unambiguous — but if a republish ever produces a
    *new* publication, recipients of the old link should NOT silently see
    the new content. Phase 8 republish flow re-issues a fresh token; old
    tokens are revoked at the same time.
    """
    __tablename__ = "share_links"
    __table_args__ = (
        Index("ix_share_links_assessment_active", "assessment_id", "revoked_at"),
    )

    id = Column(Integer, primary_key=True, index=True)
    token = Column(String(64), unique=True, nullable=False, index=True)
    assessment_id = Column(
        Integer,
        ForeignKey("assessments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    issued_by_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    label = Column(String(120), nullable=True)  # e.g. "Q4 board review"
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    expires_at = Column(DateTime, nullable=False, index=True)
    revoked_at = Column(DateTime, nullable=True)
    last_accessed_at = Column(DateTime, nullable=True)
    access_count = Column(Integer, default=0, nullable=False)

    assessment = relationship("Assessment")

    def is_active(self, now: datetime) -> bool:
        return self.revoked_at is None and self.expires_at > now

    def __repr__(self) -> str:
        return f"<ShareLink id={self.id} assessment_id={self.assessment_id}>"
