"""phase 4 response skip state

Revision ID: 16238f6c3561
Revises: 3c3cb2b363f7
Create Date: 2026-04-25 20:45:33.439334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16238f6c3561'
down_revision: Union[str, Sequence[str], None] = '3c3cb2b363f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('responses', schema=None) as batch_op:
        # server_default='0' so existing rows backfill cleanly. Drop the
        # default after the column is in place; new inserts come from the
        # ORM with an explicit value.
        # sa.false() renders as `false` on Postgres and `0` on SQLite, so
        # the same migration works on both engines. Plain sa.text('0')
        # passes on SQLite but Postgres rejects it ("column is of type
        # boolean but default expression is of type integer").
        batch_op.add_column(
            sa.Column('skipped', sa.Boolean(), nullable=False, server_default=sa.false()),
        )
        batch_op.add_column(sa.Column('skip_reason', sa.String(length=32), nullable=True))
        batch_op.alter_column('value', existing_type=sa.INTEGER(), nullable=True)
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('skipped', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('skip_reason')
        batch_op.drop_column('skipped')

    # ### end Alembic commands ###
