"""phase 5 findings + annotations + publications

Revision ID: 1e13623f48c6
Revises: 16238f6c3561
Create Date: 2026-04-25 21:14:37.112159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e13623f48c6'
down_revision: Union[str, Sequence[str], None] = '16238f6c3561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('cover_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', name='uq_publications_assessment')
    )
    with op.batch_alter_table('assessment_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_publications_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_publications_id'), ['id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.String(length=16), nullable=False),
    sa.Column('finding_template_id', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('finding_text', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('regulatory_risk', sa.Text(), nullable=True),
    sa.Column('typical_consulting_hours', sa.Integer(), nullable=True),
    sa.Column('upsell_hook', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_assessment_dimension', ['assessment_id', 'dimension_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_finding_template_id'), ['finding_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_id'), ['id'], unique=False)

    op.create_table('finding_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('new_severity', sa.String(length=16), nullable=True),
    sa.Column('new_finding_text', sa.Text(), nullable=True),
    sa.Column('new_recommendation', sa.Text(), nullable=True),
    sa.Column('new_regulatory_risk', sa.Text(), nullable=True),
    sa.Column('new_hours', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_annotations', schema=None) as batch_op:
        batch_op.create_index('ix_finding_annotations_finding_created', ['finding_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_annotations_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_annotations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_annotations_id'))
        batch_op.drop_index(batch_op.f('ix_finding_annotations_finding_id'))
        batch_op.drop_index('ix_finding_annotations_finding_created')

    op.drop_table('finding_annotations')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_id'))
        batch_op.drop_index(batch_op.f('ix_findings_finding_template_id'))
        batch_op.drop_index(batch_op.f('ix_findings_assessment_id'))
        batch_op.drop_index('ix_findings_assessment_dimension')

    op.drop_table('findings')
    with op.batch_alter_table('assessment_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_publications_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_publications_assessment_id'))

    op.drop_table('assessment_publications')
    # ### end Alembic commands ###
