"""phase 6b tenant jurisdiction codes

Revision ID: 7806cb99658d
Revises: 1e13623f48c6
Create Date: 2026-04-25 23:39:52.989066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7806cb99658d'
down_revision: Union[str, Sequence[str], None] = '1e13623f48c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurisdiction_codes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('jurisdiction_codes')

    # ### end Alembic commands ###
