"""phase 9 response answered_by_id

Revision ID: 7f8786eb8876
Revises: f64c556a8d84
Create Date: 2026-04-26 00:59:23.139569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8786eb8876'
down_revision: Union[str, Sequence[str], None] = 'f64c556a8d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_responses_answered_by_id_users',
            'users',
            ['answered_by_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_responses_answered_by_id_users', type_='foreignkey')
        batch_op.drop_column('answered_by_id')

    # ### end Alembic commands ###
