"""phase 8 share_links

Revision ID: 874a8d558229
Revises: 7806cb99658d
Create Date: 2026-04-26 00:37:28.305522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874a8d558229'
down_revision: Union[str, Sequence[str], None] = '7806cb99658d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index('ix_share_links_assessment_active', ['assessment_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_token'))
        batch_op.drop_index(batch_op.f('ix_share_links_id'))
        batch_op.drop_index(batch_op.f('ix_share_links_expires_at'))
        batch_op.drop_index(batch_op.f('ix_share_links_assessment_id'))
        batch_op.drop_index('ix_share_links_assessment_active')

    op.drop_table('share_links')
    # ### end Alembic commands ###
