"""phase 8 publication unpublished_at

Revision ID: f64c556a8d84
Revises: 08629d8dd8bc
Create Date: 2026-04-26 00:43:51.196772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64c556a8d84'
down_revision: Union[str, Sequence[str], None] = '08629d8dd8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unpublished_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_publications', schema=None) as batch_op:
        batch_op.drop_column('unpublished_at')

    # ### end Alembic commands ###
